---
- name: Remove 'v' prefix from asdf_version
  ansible.builtin.set_fact:
    clean_asdf_version: "{{ asdf_version | regex_replace('^v', '') }}"
  tags: [asdf, asdf-install]

- name: install asdf >= v0.16
  ansible.builtin.import_tasks: "install_go.yml"
  tags: [asdf, asdf-install]
  when: clean_asdf_version is version(asdf_go_version, '>=')

- name: "install asdf < v0.16"
  ansible.builtin.import_tasks: "install_bash.yml"
  tags: [asdf, asdf-install]
  when: clean_asdf_version is version(asdf_go_version, '<')

- name: "install plugins"
  ansible.builtin.import_tasks: "plugins.yml"
  tags: [asdf, asdf-plugins]
